name: SROS2 CI
on:
  pull_request:
  push:
  schedule:
    # Run daily
    - cron:  '0 12 * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
    - uses: ros-tooling/setup-ros@0.0.15
    - uses: ros-tooling/action-ros-ci@0.0.14
      with:
        package-name: |
          sros2
          sros2_cmake
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: colcon-logs
        path: ros_ws/log

  # Linter jobs
  ament_copyright:
    name: ament_${{ matrix.linter_name }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        linter_name: [copyright]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.15
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: ${{ matrix.linter_name }}
        package-name: |
          sros2
          sros2_cmake

  # action-ros-lint does not support multi work linters like lint_cmake
  # ament_lint_cmake:
  #   name: ament_${{ matrix.linter_name }}
  #   runs-on: ubuntu-18.04
  #   strategy:
  #     matrix:
  #       linter_name: [lint-cmake]
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: ros-tooling/setup-ros@0.0.15
  #   - uses: ros-tooling/action-ros-lint@0.0.5
  #     with:
  #       linter: ${{ matrix.linter_name }}
  #       package-name: |
  #         sros2_cmake

  ament_xmllint:
    name: ament_${{ matrix.linter_name }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        linter_name: [xmllint]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.15
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: ${{ matrix.linter_name }}
        package-name: |
          sros2_cmake
        # Comment out sros2 for now because xmllint doesnt support https
        # more details at https://github.com/ament/ament_lint/pull/104#issuecomment-404701186
        # sros2

  ament_lint_python: # Linters applicable to Python packages
    name: ament_${{ matrix.linter_name }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
          linter_name: [flake8, pep257, mypy]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.15
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: ${{ matrix.linter_name }}
        package-name: |
          sros2
