name: Test Container

on: [push]

jobs:
  source:
    runs-on: ubuntu-18.04
    container: osrf/ros2:devel
    env:
      ROS_DISTRO: foxy
    steps:
    - uses: actions/checkout@v1
    - run: |
            apt-get update
            apt-get -qq upgrade -y
            apt-get -qq install -y curl
            curl -sk https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos > ros2.repos
            mkdir src
            vcs import src < ros2.repos
    - run: |
        diff --new-line-format="" --unchanged-line-format="" <(colcon list -p) <(colcon list --packages-up-to sros2 sros2_cmake -p) | xargs rm -rf
        rosdep update --rosdistro $ROS_DISTRO
        rosdep install -y --from-paths src --ignore-src
    # - run: |
    #   colcon build --packages-up-to rcutils
      
  # nightly:
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: docker://osrf/ros2:nightly
  #   - 
