name: ICI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {DOCKER_IMAGE: "osrf/ros2:nightly", UPSTREAM_WORKSPACE: additional_repos.repos}
          - {ROS_DISTRO: eloquent, ROS_REPO: testing}
          - {ROS_DISTRO: eloquent, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
