# Run linters automatically on pull requests.
name: Lint sros2 repo
on:
  pull_request:

jobs:
  ament_copyright:
    name: ament_copyright
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: copyright
        package-name: |
          sros2
          sros2_cmake

  ament_lint_cmake:
    name: ament_lint_cmake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: copyright
        package-name: |
          sros2_cmake

  ament_xmllint:
    name: ament_xmllint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: xmllint
        package-name: |
          sros2_cmake
        # Comment out sros2 for now because xmllint doesnt support https
        # more details at https://github.com/ament/ament_lint/pull/104#issuecomment-404701186
        # sros2

  ament_lint_python: # Linters applicable to Python packages
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [flake8, pep257, mypy]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: ${{ matrix.linter }}
        package-name: |
          sros2
