name: Brew openssl
on:
  pull_request:
  push:
  schedule:
    # Run daily
    - cron:  '0 20 * * *'

jobs:
  test_macos:
    runs-on: macos-latest
    steps:
    -  run: |
        brew update
        brew upgrade openssl@1.1
    - run: |
        brew update
        brew install openssl@1.0.2t
    - run: brew --prefix openssl
    - run: brew --prefix openssl@1.1
    - run: brew --prefix openssl@1.0.2t
    - run: brew --prefix openssl@1.0
