name: Test sros2
on:
  pull_request:
  push:
  schedule:
    # Run daily
    - cron:  '0 12 * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - {JOB_TYPE: nightly, MIXIN_BUILD: "release", COVERAGE: "codecov"}
        - {JOB_TYPE: nightly, MIXIN_BUILD: "debug"}
        # - {JOB_TYPE: eloquent}
    steps:
    - uses: actions/checkout@v1
    - name: build and test
      run: |
            cd ${GITHUB_WORKSPACE}
            git clone --quiet --depth 1 https://github.com/mikaelarguedas/ros2ci.git -b actions_support .ros2ci
            .ros2ci/top_level_ci.bash $JOB_TYPE
      env: ${{matrix.env}}
