name: Test sros2
on:
  pull_request:
  push:
  schedule:
    # Run daily
    - cron:  '0 12 * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: |
          sros2
          sros2_cmake
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        file: ros_ws/src/sros2/sros2/coverage.xml
        flags: unittests
        name: sros2-coverage
        fail_ci_if_error: true
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: colcon-logs
        path: ros_ws/log
